apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-k8s-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-k8s-app-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30